### PR TITLE
Extend exercise 8 with a loop for user prompt

### PR DESCRIPTION
**Pull request by ionescu77**
Extend exercise 8 with a loop for user prompt, remembering system instructions

### CODE REVIEW

**Review by alexmazaltov — COMMENTED** [review]
@ionescu77 If I understood correctly, this way we receive the user's request and add the neural network's response to the system instructions for further interaction. In this way, we expand the context of dialogue?

**Comment by ionescu77** [comment]
> @ionescu77 If I understood correctly, this way we receive the user's request and add the neural network's response to the system instructions for further interaction. In this way, we expand the context of dialogue?

Yes, this `while` loops keeps asking for user input, and it should remember the previous `system` context.

**Comment by ionescu77** [comment]
Let me test if it remembers context.

**Comment by ionescu77** [comment]
@alexmazaltov , fantastic. I asked and it remembered the questions asked previously:
- `sarmale` (is a romanian dish, meat chunks in rolled cabage leafs)
- second time an indian dish `chicken palak`

Check the last Q&A:

```bash
python chef-gpt-indian.py
Type the name of the dish you want a recipe for:
sarmale
```
Oh dear, sarmale! I must confess, that's not my cup of tea! I specialize in the aromatic world of Biryani, where spices dance and basmati rice sings. Unfortunately, sarmale is outside my culinary expertise. But don't worry, I’m here for all your Biryani-related needs!

Why do chefs always find the best herbs? Because they thyme everything perfectly! 😊

If you'd like a delicious Biryani recipe or any other Indian dish, just let me know!

```
chicken palak
```
Ah, chicken palak! I can definitely help you with that delicious dish. Chicken palak is a North Indian classic that blends tender chicken pieces with nutrient-packed spinach. Here’s a detailed recipe:

### Ingredients:
- **For the Chicken:**
  - 500 grams chicken, cut into pieces (boneless or with bone, as per your preference)
  - 2 tablespoons oil (vegetable or ghee)
  - 1 teaspoon cumin seeds
  - 1 large onion, finely chopped
  - 2 tablespoons ginger-garlic paste
  - 2 medium tomatoes, pureed
  - 1 teaspoon turmeric powder
  - 1 teaspoon red chili powder (adjust to taste)
  - 1 teaspoon garam masala
  - Salt to taste

- **For the Spinach:**
  - 250 grams fresh spinach (palak), washed and blanched
  - 1-2 green chilies (adjust to taste)
  - 2-3 tablespoons cream (optional, for richness)
  - 1/2 teaspoon lemon juice
  - Salt to taste

### Instructions:

#### Step 1: Prepare the Spinach Purée
1. **Blanch the Spinach**: In a pot, bring water to a boil. Add the spinach leaves for about 2-3 minutes until they wilt. Drain and immediately transfer to cold water to stop the cooking process.
2. **Make the Purée**: Once cool, blend the spinach along with green chilies until smooth. Set aside.

#### Step 2: Cook the Chicken
3. **Sauté the Cumin**: In a heavy-bottomed pan, heat the oil over medium heat. Add cumin seeds and let them splutter.
4. **Add Onions**: Add the chopped onions and sauté until golden brown.
5. **Ginger-Garlic Paste**: Stir in the ginger-garlic paste. Cook for a couple of minutes until the raw smell fades.
6. **Tomato Purée**: Add the tomato purée and cook until the oil begins to separate, about 5-7 minutes.
7. **Spices**: Add turmeric powder, red chili powder, and salt. Mix well and cook for another 2 minutes.
8. **Chicken**: Add the chicken pieces. Stir to coat them well in the masala. Cook for about 10 minutes on medium heat until the chicken is no longer pink.

#### Step 3: Combine Spinach with Chicken
9. **Add Spinach Purée**: Pour in the spinach purée and mix well. Cook for another 5 minutes, allowing the flavors to meld.
10. **Finish**: Stir in the garam masala and cream (if using). Cook for an additional 2-3 minutes. Adjust salt and add lemon juice to taste.

### Step 4: Serve
11. **Garnish**: Garnish with additional cream or fresh coriander if desired.
12. **Accompaniment**: Serve hot with rice or Indian bread (like naan or roti).

### Tips:
- You can add some boiled potatoes along with the chicken for extra texture and taste.
- For a smoky flavor, you can add a piece of charcoal in the pan while covering it for a few minutes.
- Adjust the spice levels according to your preference; you can use mild green chilies for less heat.

And there you have it, a delightful Chicken Palak recipe! Enjoy the vibrant color and the rich flavors! If you need any more tips or have questions, feel free to ask!

Why did the chicken join a band? Because it had the drumsticks! 🥁🐔
```
What questions did I ask you until now?
```
You asked for a detailed recipe and preparation steps for making sarmale, and then you asked for a recipe for chicken palak. If you have more questions or need further assistance with any recipes, feel free to ask! I'm here to help! 😊

**Pull request merged**
